// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbnegergyzhnwxealmdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibmVnZXJneXpobnd4ZWFsbWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTQ3NzcsImV4cCI6MjA1ODQ3MDc3N30.e0lzY0BtyOe4HbXWyaLfxhhZbw33ZeCJY-FMtlrneoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);